image: node:16

stages:
  - install
  - build

cache:
  paths:
    - group6/node_modules/

install_dependencies:
  stage: install
  script:
    - cd group6
    - npm install
  only:
    - merge_requests
    - main

build:
  stage: build
  script:
    - cd group6
    - npm run build
  artifacts:
    paths:
      - group6/.next
  only:
    - merge_requests
    - main
