stages:
  - build
  # - b_post
  # - b_unit
  # - f_jest
  # - f_sel

build_frontend:
  stage: build
  image: node:latest
  cache:
    paths:
      - ./group6/src/.next/cache/  # Assuming Next.js is used, and the cache directory is .next/cache/
  script:
      - ls -la  # List all files and directories for debugging purposes
      - cd src  # This is where your Next.js app seems to be located
      - npm install
      - npm run build  # You may need a build script in your package.json

# build-job:
#   stage: build
#   script:
#     - echo "Hello, $GITLAB_USER_LOGIN!"
