stages:
  - build
  # - b_post
  # - b_unit
  # - f_jest
  # - f_sel

build_frontend:
  stage: build
  image: node:latest
  cache:
    paths:
      - ./group6/node_modules/
      - ./group6/.next/cache/
  script:
      - cd group6  # Change into the 'group6' directory where your Next.js app is located
      - npm install
      - npm run build

# build-job:
#   stage: build
#   script:
#     - echo "Hello, $GITLAB_USER_LOGIN!"
