"""Making minor changes to the support group table

Revision ID: d7b29567daa9
Revises: 88842cfb34b5
Create Date: 2024-03-05 23:52:29.443748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7b29567daa9'
down_revision = '88842cfb34b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_groups_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mission_stmt', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('picture_url', sa.Text(), nullable=False))
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.drop_column('region')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_groups_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', mysql.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('rating',
               existing_type=sa.Double(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('picture_url')
        batch_op.drop_column('mission_stmt')

    # ### end Alembic commands ###
